---
- name: Ensure Podman is installed
  package:
    name:
      - podman
      - podman-docker
      - python3-podman

- name: Ensure data path volume exists
  containers.podman.podman_volume:
    state: present
    name: "rally_volume"

- name: Run Rally container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    command: 'deployment create'
    image: "{{ container_image }}"
    volume:
      - "rally_volume:/home/rally/.rally"
    state: started
...
