---
- name: Set Rally configuration file variable
  set_fact:
    rally_config_file: /home/rally/.rally/rally.conf

- name: Ensure Podman is installed
  package:
    name:
      - podman
      - podman-docker
      - python3-podman

- name: Create group for Rally
  group:
    name: rally
    gid: 65500
    state: present
    system: yes

- name: Create user for Rally
  user:
    name: rally
    uid: 65500
    groups: rally
    shell: /bin/bash
    state: present
    system: yes
    createhome: yes
    home: /home/rally

- name: Ensure Rally home exists
  file:
    state: directory
    name: /home/rally
    owner: 65500

- name: Ensure Rally/tmp exists
  file:
    state: directory
    name: /home/rally/tmp
    owner: 65500

- name: Ensure Rally/rally exists
  file:
    state: directory
    name: /home/rally/rally
    owner: 65500

- name: Ensure Rally/rally/etc exists
  file:
    state: directory
    name: /home/rally/rally/etc
    owner: 65500

- name: Ensure Rally/rally/etc/rally exists
  file:
    state: directory
    name: /home/rally/rally/etc/rally
    owner: 65500

- name: Ensure rally.conf exists
  file:
    state: touch
    name: /home/rally/rally/etc/rally/rally.conf
    owner: 65500

- name: Rally configure swift operator role (container)
  ini_file:
    path: "/home/rally/rally/etc/rally/rally.conf"
    section: openstack
    option: swift_operator_role
    value: "{{ rally_tempest_swift_operator_role }}"
  when: rally_tempest_swift_operator_role is defined

- name: Rally configure swift reseller admin role (container)
  ini_file:
    path: "/home/rally/rally/etc/rally/rally.conf"
    section: openstack
    option: "swift_reseller_admin_role"
    value: "{{ rally_tempest_swift_reseller_admin_role }}"
  when: rally_tempest_swift_reseller_admin_role is defined

- name: Clone repo for container
  git:
    repo: "{{ custom_container_repo }}"
    dest: /tmp/rally_container
    version: "{{ custom_container_repo_branch }}"
    update: true
    force: true
  when:
    - custom_container_repo is defined
    - custom_container_repo != ''

- name: Build custom container
  shell:
    cmd: podman build -t {{ container_name }} /tmp/rally_container
  environment: "{{proxy_env}}"
  when:
    - custom_container_repo is defined
    - custom_container_repo != ''

- name: Run Rally container to create database
  containers.podman.podman_container:
    name: "db_create_{{ container_name }}"
    command: "db create"
    image: "{{ container_image }}"
    volume:
      - "/home/rally/tmp:/tmp"
      - "/home/rally:/home/rally/.rally"
      - "/home/rally/rally/etc/rally/rally.conf:/home/rally/.rally/rally.conf"
    state: started

- name: Ensure Rally .rally folder exists
  file:
    path: /home/rally/.rally
    state: directory
    owner: rally

- name: Ensure Rally bin folder exists
  file:
    path: /home/rally/rally/bin
    state: directory
    owner: rally

- name: Ensure Rally deployments folder exists
  file:
    path: /home/rally/deployments
    state: directory
    owner: rally

- name: store tempest configs in a persistent place
  file:
    state: directory
    path: /home/rally/tempest_configs
    mode: 0700
    owner: rally
    group: rally

...
