---
- name: Set Rally configuration file variable
  set_fact:
    rally_config_file: /home/rally/.rally/rally.conf

- name: Ensure Podman is installed
  package:
    name:
      - podman
      - podman-docker
      - python3-podman

- name: Ensure Rally home exists
  file:
    state: directory
    name: /home/rally
    owner: 65500

- name: Ensure Rally/rally exists
  file:
    state: directory
    name: /home/rally/rally
    owner: 65500

- name: Ensure Rally/rally/etc exists
  file:
    state: directory
    name: /home/rally/rally/etc
    owner: 65500

- name: Ensure Rally/rally/etc/rally exists
  file:
    state: directory
    name: /home/rally/rally/etc/rally
    owner: 65500

- name: Ensure rally.conf exists
  file:
    state: directory
    name: /home/rally/rally/etc/rally/rally.conf
    owner: 65500

- name: Run Rally container to create database
  containers.podman.podman_container:
    name: "{{ container_name }}"
    command: "db create"
    image: "{{ container_image }}"
    volume:
      - "/home/rally:/home/rally/.rally"
      - "/home/rally/rally/etc/rally/rally.conf:/home/rally/.rally/rally.conf"
    state: started
...
