---
- name: Install dependencies
  yum: name={{item}} state=installed
  with_items:
  - "python2-pip"
  - "wget"
  - "sqlite"
  - "python-devel"
  - "openssl-devel"
  - "git"
  - "libffi-devel"
  - "gcc"
  - "libxml2-devel"
  - "libxslt-devel"

- name: Create group for Rally
  group: name=rally state=present system=yes

- name: Create user for Rally
  user: name=rally groups=rally shell=/bin/bash state=present system=yes createhome=yes home=/home/rally

- name: Create Rally directories
  file: path={{ item.path }} state=directory owner=rally group=rally mode=0750
  with_items:
    - path: "/etc/rally"
    - path: "/home/rally"

- name: Get Rally installation script
  get_url: url=https://raw.githubusercontent.com/openstack/rally/master/install_rally.sh mode=0776 owner=rally group=rally dest=/tmp

- name: Install rally
  become_user: rally
  command: /tmp/install_rally.sh

- name: Clean up
  yum: name={{item}} state=absent
  with_items:
  - "python-devel"
  - "openssl-devel"
  - "libxml2-devel"
  - "libxslt-devel"
  - "gcc"
